1. INSTALACION E IMPORTACION DE LIBRERIAS

In [57]:
import numpy as np
import pandas as pd

2. CARGA DE DATOS

In [58]:
df_banco = pd.read_csv("C:/Users/sarav/Documents/Cursos/Data analytics The Power/7. Python for data/PROYECTO/DatosProyecto/bank-additional.csv")

In [59]:
df_cliente = pd.read_excel("C:/Users/sarav/Documents/Cursos/Data analytics The Power/7. Python for data/PROYECTO/DatosProyecto/customer-details.xlsx")

3. LIMPIEZA DE DATOS

3.1. info general

In [60]:
df_banco.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: float64(7), int64(5), str(12)
memory usage: 7.9 MB

In [61]:

df_banco.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,...,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,...,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,...,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,...,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,...,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

hay varias columnas que salen como str y deberian ser numericas. Además, la columna de fecha no tiene formato de fecha

In [62]:
df_cliente.info()

<class 'pandas.DataFrame'>
RangeIndex: 20115 entries, 0 to 20114
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         20115 non-null  int64
 1   Income             20115 non-null  int64
 2   Kidhome            20115 non-null  int64
 3   Teenhome           20115 non-null  int64
 4   Dt_Customer        20115 non-null  datetime64[us]
 5   NumWebVisitsMonth  20115 non-null  int64
 6   ID                 20115 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.1 MB

In [63]:
df_cliente.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

Formato de las columnas correcto

3.2. Valores nulos

In [64]:
df_banco.isnull()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42995,False,True,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
42996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
42997,False,True,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
42998,False,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
42999,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [65]:
df_banco.isnull().sum()

Unnamed: 0           0
age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
dtype: int64

Bastantes valores nulos

In [66]:
df_cliente.isnull()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
20110,False,False,False,False,False,False,False
20111,False,False,False,False,False,False,False
20112,False,False,False,False,False,False,False
20113,False,False,False,False,False,False,False
20114,False,False,False,False,False,False,False

In [67]:
df_cliente.isnull().sum()

Unnamed: 0           0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
NumWebVisitsMonth    0
ID                   0
dtype: int64

No se ven valores nulos

3.3. Valores NA

In [68]:
df_banco.isna().sum()

Unnamed: 0           0
age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
contact              0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx     471
cons.conf.idx        0
euribor3m         9256
nr.employed          0
y                    0
date               248
latitude             0
longitude            0
id_                  0
dtype: int64

Veo los valores únicos de job:

In [69]:
df_banco['job'].unique()

<StringArray>
[    'housemaid',      'services',        'admin.',   'blue-collar',
    'technician',       'retired',    'management',    'unemployed',
 'self-employed',             nan,  'entrepreneur',       'student']
Length: 12, dtype: str

se ve que uno de las opciones que salen es nan. 
Muchos valores NaN en varios campos

In [70]:
df_cliente.isna().sum()

Unnamed: 0           0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
NumWebVisitsMonth    0
ID                   0
dtype: int64

No tiene valores no aplica.

3.4. Filas duplicadas

In [71]:
df_banco.duplicated().sum()

np.int64(0)

In [72]:
df_cliente.duplicated().sum()

np.int64(0)

No hay filas duplicadas en ninguno.
Se puede determinar que los datos de cliente no tienen limpieza que aplicarle, por lo que me focalizaré en limpiar banco.

4. LIMPIEZA BANCO

4.1 Eliminar columnas innecesarias

In [73]:
df_banco.drop('Unnamed: 0',axis = 1,inplace = True)

In [74]:
df_cliente.drop('Unnamed: 0',axis = 1,inplace = True)

In [75]:
df_banco.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [76]:
df_cliente.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

4.2. Arreglar columnas texto a numericas - cons.pride.idx

In [77]:
df_banco['cons.price.idx'] = df_banco['cons.price.idx'].apply(
    lambda x: float(str(x).replace(",", ".")) 
    if pd.notnull(x) and str(x) != "False" 
    else None
    )

In [78]:
df_banco.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,1.1,93.994,"-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,1.1,93.994,"-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,1.1,93.994,"-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,1.1,93.994,"-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,1.1,93.994,"-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [79]:
df_banco['cons.price.idx'].dtype

dtype('float64')

4.2. Arreglar columnas texto a numericas - cons.conf.idx

In [80]:
df_banco['cons.conf.idx'] = df_banco['cons.conf.idx'].apply(
    lambda x: float(str(x).replace(",", ".")) 
    if pd.notnull(x) and str(x) != "False" 
    else None
    )

In [81]:
df_banco.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,1.1,93.994,-36.4,"4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,1.1,93.994,-36.4,NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,1.1,93.994,-36.4,"4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,1.1,93.994,-36.4,NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,1.1,93.994,-36.4,NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [82]:
df_banco['cons.conf.idx'].dtype

dtype('float64')

4.2. Arreglar columnas texto a numericas - euribor3m

In [83]:
df_banco['euribor3m'] = df_banco['euribor3m'].apply(
    lambda x: float(str(x).replace(",", ".")) 
    if pd.notnull(x) and str(x) != "False" 
    else None
    )

In [84]:
df_banco.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,1.1,93.994,-36.4,4.857,5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,1.1,93.994,-36.4,NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,1.1,93.994,-36.4,4.857,5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,1.1,93.994,-36.4,NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,1.1,93.994,-36.4,NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [85]:
df_banco['euribor3m'].dtype

dtype('float64')

4.2. Arreglar columnas texto a numericas - nr.employed

In [86]:
df_banco['nr.employed'] = df_banco['nr.employed'].apply(
    lambda x: float(str(x).replace(",", ".")) 
    if pd.notnull(x) and str(x) != "False" 
    else None
    )

In [87]:
df_banco.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,1.1,93.994,-36.4,4.857,5191.0,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,1.1,93.994,-36.4,NaN,5191.0,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,1.1,93.994,-36.4,4.857,5191.0,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,1.1,93.994,-36.4,NaN,5191.0,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,1.1,93.994,-36.4,NaN,5191.0,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [88]:
df_banco['nr.employed'].dtype

dtype('float64')

4.3. Arreglar columna fecha

In [89]:
df_banco['date'].head()

0         2-agosto-2019
1    14-septiembre-2016
2       15-febrero-2019
3     29-noviembre-2015
4         29-enero-2017
Name: date, dtype: str

Tengo que transformar las palabras en español de los meses a numeros. Primero creo un diccionario con los meses

In [90]:
meses = {
    "enero": "01",
    "febrero": "02",
    "marzo": "03",
    "abril": "04",
    "mayo": "05",
    "junio": "06",
    "julio": "07",
    "agosto": "08",
    "septiembre": "09",
    "octubre": "10",
    "noviembre": "11",
    "diciembre": "12"
}

Defino la función de cambio de meses, la aplico y cambio a formato fecha

In [91]:
def cambiar_mes(fecha):
    if pd.notnull(fecha):
        fecha = str(fecha)
        for mes, num in meses.items():
            if mes in fecha:
                fecha = fecha.replace(mes, num)
        return fecha
    return fecha

df_banco['date'] = df_banco['date'].apply(cambiar_mes)

df_banco['date'] = pd.to_datetime(df_banco['date'], format='%d-%m-%Y')

Compruebo:

In [92]:
df_banco['date'].dtype
df_banco['date'].head()

0   2019-08-02
1   2016-09-14
2   2019-02-15
3   2015-11-29
4   2017-01-29
Name: date, dtype: datetime64[us]

4.4. Analizar nulos y decidir
Ya he sacado cuantos nulos, tengo que ver cuanto representan del total

In [93]:
(df_banco.isnull().sum() / len(df_banco)) * 100

age               11.906977
job                0.802326
marital            0.197674
education          4.202326
default           20.886047
housing            2.386047
loan               2.386047
contact            0.000000
duration           0.000000
campaign           0.000000
pdays              0.000000
previous           0.000000
poutcome           0.000000
emp.var.rate       0.000000
cons.price.idx     1.095349
cons.conf.idx      0.000000
euribor3m         21.525581
nr.employed        0.000000
y                  0.000000
date               0.576744
latitude           0.000000
longitude          0.000000
id_                0.000000
dtype: float64

Frecuencia baja (<5%) - voy a dejarlos y cambiarlos por la palabra "unknown"

In [94]:
df_banco['job'] = df_banco['job'].fillna('unknown')
df_banco['marital'] = df_banco['marital'].fillna('unknown')
df_banco['education'] = df_banco['education'].fillna('unknown')
df_banco['housing'] = df_banco['housing'].fillna('unknown')
df_banco['loan'] = df_banco['loan'].fillna('unknown')

In [95]:
df_banco['cons.price.idx'] = df_banco['cons.price.idx'].fillna(df_banco['cons.price.idx'].mean())

In [96]:
df_banco = df_banco.dropna(subset=['date'])

Frecuencia media (<15%) - sustituyo nulos por la media

In [97]:
df_banco['age'] = df_banco['age'].fillna(df_banco['age'].mean())

Frecuencia alta - tratamiento. Default sustituyo por ceros

In [98]:
df_banco['default'] = df_banco['default'].fillna(0)

Frecuencia alta - tratamiento. Euribor sustituyo por media

In [99]:
df_banco['euribor3m'] = df_banco['euribor3m'].fillna(df_banco['euribor3m'].mean())

In [100]:
df_banco.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
date              0
latitude          0
longitude         0
id_               0
dtype: int64

5. MERGE/UNION DE ARCHIVOS

In [101]:
df_final = df_banco.merge(df_cliente, how = 'left', left_on = 'id_', right_on = 'ID')

6. REVISION DE DATOS DEL CONJUNTO GLOBAL

In [102]:
df_final.shape
df_final.head()
df_final.isnull().sum()

age                      0
job                      0
marital                  0
education                0
default                  0
housing                  0
loan                     0
contact                  0
duration                 0
campaign                 0
pdays                    0
previous                 0
poutcome                 0
emp.var.rate             0
cons.price.idx           0
cons.conf.idx            0
euribor3m                0
nr.employed              0
y                        0
date                     0
latitude                 0
longitude                0
id_                      0
Income               22843
Kidhome              22843
Teenhome             22843
Dt_Customer          22843
NumWebVisitsMonth    22843
ID                   22843
dtype: int64

7. ANALISIS

In [103]:
df_final['y'].value_counts()

y
no     37941
yes     4811
Name: count, dtype: int64

7.1. Job vs contratacion

In [104]:
df_final.groupby('job')['y'].value_counts(normalize=True)

job            y
admin.         no     0.870209
               yes    0.129791
blue-collar    no     0.931078
               yes    0.068922
entrepreneur   no     0.917826
               yes    0.082174
housemaid      no     0.900627
               yes    0.099373
management     no     0.888669
               yes    0.111331
retired        no     0.747475
               yes    0.252525
self-employed  no     0.891436
               yes    0.108564
services       no     0.919468
               yes    0.080532
student        no     0.686384
               yes    0.313616
technician     no     0.891609
               yes    0.108391
unemployed     no     0.855524
               yes    0.144476
unknown        no     0.886628
               yes    0.113372
Name: proportion, dtype: float64

7.2. Edad vs contratacion

In [105]:
df_final.groupby('y')['age'].describe()

       count      mean        std   min   25%        50%   75%   max
y
no   37941.0  39.87699   9.313233  17.0  33.0  39.980698  45.0  95.0
yes   4811.0  40.79857  12.998378  17.0  31.0  39.000000  48.0  98.0

7.3. Contact vs contratación

In [106]:
df_final.groupby('contact')['y'].value_counts(normalize=True)

contact    y
cellular   no     0.852710
           yes    0.147290
telephone  no     0.948454
           yes    0.051546
Name: proportion, dtype: float64

7.4. Duración llamada vs contratacion

In [107]:
df_final.groupby('y')['duration'].mean()

y
no     220.386205
yes    552.556017
Name: duration, dtype: float64

7.5. Poutcome vs contratacion

In [108]:
df_final.groupby('poutcome')['y'].value_counts(normalize=True)

poutcome     y
FAILURE      no     0.857979
             yes    0.142021
NONEXISTENT  no     0.911965
             yes    0.088035
SUCCESS      yes    0.654278
             no     0.345722
Name: proportion, dtype: float64